CREATE USER admin_django IDENTIFIED BY admin1234;

GRANT ALL PRIVILEGES TO admin_django;

GRANT EXECUTE ANY PROCEDURE TO admin_django;
GRANT UNLIMITED TABLESPACE TO admin_django;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

/

CREATE OR REPLACE PROCEDURE SP_SALDOS(SP_SALDOS OUT SYS_REFCURSOR) IS
    BEGIN
    OPEN SP_SALDOS FOR 
        SELECT
            STOCK.ID_STOCK,
            VENTA.ID_VENTA_LOCAL,
            STOCK.FECHA_COSECHA,
            STOCK.FECHA_ESTIMADA_VENCIMIENTO,
            ESPECIE.DES_ESPECIE,
            VARIEDAD.DES_VARIEDAD,
            STOCK.KILOS,
            STOCK.PRECIO_KILO,
            REPLACE(IMAGEN.DESC_IMAGEN, ' ', '-'),
            IMAGEN.EXT_IMAGEN,
            IMAGEN.IMAGEN AS IMAGEN,
            CASE
                WHEN VENTA.ID_ESTADO IS NULL THEN 1
                ELSE VENTA.ID_ESTADO
            END AS ESTADO_VENTA,
            ROW_NUMBER()OVER (PARTITION BY VARIEDAD.DES_VARIEDAD ORDER BY STOCK.FECHA_ESTIMADA_VENCIMIENTO DESC) AS N_REP_FRUTA
        FROM
            STOCK_SOBRANTE STOCK
                LEFT JOIN VENTA_LOCAL VENTA
                    ON STOCK.ID_STOCK = VENTA.ID_STOCK AND VENTA.ID_VENTA_LOCAL = (SELECT MAX(VENTA_2.ID_VENTA_LOCAL) FROM VENTA_LOCAL VENTA_2 WHERE VENTA_2.ID_STOCK = VENTA.ID_STOCK)
                INNER JOIN VARIEDAD VARIEDAD
                    ON STOCK.ID_VARIEDAD = VARIEDAD.ID_VARIEDAD
                INNER JOIN ESPECIE ESPECIE
                    ON VARIEDAD.ID_ESPECIE = ESPECIE.ID_ESPECIE
                LEFT JOIN IMAGEN IMAGEN
                    ON VARIEDAD.ID_IMAGEN = IMAGEN.ID_IMAGEN
        WHERE
            VENTA.ID_ESTADO = 1 OR VENTA.ID_ESTADO IS NULL
        ORDER BY
            VARIEDAD.DES_VARIEDAD;
    EXCEPTION --control de excepciones
        WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END SP_SALDOS;

/

CREATE OR REPLACE PROCEDURE SP_SOLICITUDES_ACEPTADAS AS
    BEGIN
        INSERT INTO ORDEN_COMPRA
            (ID_ORDEN, DIFERENCIA_FRUTA,ID_VARIEDAD, ID_SOLICITUD, ID_ESTADO)
        SELECT 
            SQ_ID_ORDEN.NEXTVAL,
            DETA_OFER.KILOS_TOTAL - DETA_SOLI.KILOS DIFF_KILOS,
            DETA_SOLI.ID_VARIEDAD,
            DETA_SOLI.ID_SOLICITUD,
            1 AS ESTADO_PEDIDO
        FROM DETALLE_SOLICITUD DETA_SOLI
            INNER JOIN SOLICITUD SOLI
                ON DETA_SOLI.ID_SOLICITUD = SOLI.ID_SOLICITUD
            INNER JOIN OFERTA_PRODUCTOR OFER_PROD
                ON SOLI.ID_SOLICITUD = OFER_PROD.ID_SOLICITUD
            INNER JOIN DETALLE_OFERTA DETA_OFER 
                ON OFER_PROD.ID_OFERTA = DETA_OFER.ID_OFERTA AND DETA_SOLI.ID_VARIEDAD = DETA_OFER.ID_VARIEDAD
        WHERE
            SOLI.ID_ESTADO = 2;-- AND DETA_SOLI.ID_SOLICITUD NOT IN (SELECT ID_SOLICITUD FROM ORDEN_COMPRA);
END SP_SOLICITUDES_ACEPTADAS;

/

CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_STOCK AS
    BEGIN
        INSERT INTO STOCK_SOBRANTE
            (ID_STOCK, ID_ORDEN, KILOS, ID_VARIEDAD, FECHA_COSECHA, FECHA_ESTIMADA_VENCIMIENTO, PRECIO_KILO)
        SELECT
            SQ_ID_STOCK.NEXTVAL,
            ORDE_COMP.ID_ORDEN,
            ORDE_COMP.DIFERENCIA_FRUTA,
            ORDE_COMP.ID_VARIEDAD,
            DETA_OFER.FECHA_COSECHA,
            DETA_OFER.FECHA_COSECHA + VARI.DIAS_VENCIMIENTO,
            ROUND((DETA_OFER.PRECIO_TOTAL/DETA_OFER.KILOS_TOTAL)*1.5)
        FROM ORDEN_COMPRA ORDE_COMP
            INNER JOIN SOLICITUD SOLI
                ON ORDE_COMP.ID_SOLICITUD = SOLI.ID_SOLICITUD
            INNER JOIN DETALLE_SOLICITUD DETA_SOLI
                ON SOLI.ID_SOLICITUD = DETA_SOLI.ID_SOLICITUD AND ORDE_COMP.ID_VARIEDAD = DETA_SOLI.ID_VARIEDAD
            INNER JOIN OFERTA_PRODUCTOR OFER_PROD
                ON SOLI.ID_SOLICITUD = OFER_PROD.ID_SOLICITUD
            INNER JOIN DETALLE_OFERTA DETA_OFER 
                ON OFER_PROD.ID_OFERTA = DETA_OFER.ID_OFERTA AND DETA_SOLI.ID_VARIEDAD = DETA_OFER.ID_VARIEDAD
            INNER JOIN VARIEDAD VARI
                ON ORDE_COMP.ID_VARIEDAD = VARI.ID_VARIEDAD
        WHERE
            ORDE_COMP.ID_ORDEN NOT IN (SELECT ID_ORDEN FROM STOCK_SOBRANTE);
END SP_ACTUALIZAR_STOCK;

/

CREATE OR REPLACE VIEW VIEW_LISTA_SOLICITUDES AS (
    SELECT
        SOLI.ID_SOLICITUD,
        SOLI.ID_USUARIO,
        SOLI.FECHA_CREACION,
        SOLI.PUB_HORA_INI,
        SOLI.PUB_HORA_FIN,
        ESPE.DES_ESPECIE,
        VARI.DES_VARIEDAD,
        DETA.KILOS,
        DETA.KILOS_OBTE,
        DETA.ID_PEDIDO,
        SOLI.ID_ESTADO,
        SOLI.ID_PUBLICACION
    FROM SOLICITUD SOLI
        INNER JOIN DETALLE_SOLICITUD DETA
            ON SOLI.ID_SOLICITUD = DETA.ID_SOLICITUD
        INNER JOIN VARIEDAD VARI
            ON DETA.ID_VARIEDAD = VARI.ID_VARIEDAD
        INNER JOIN ESPECIE ESPE
            ON VARI.ID_ESPECIE = ESPE.ID_ESPECIE
);

/

CREATE OR REPLACE VIEW VIEW_OFERTAS_PRODUCTOR AS (
    SELECT
        DETA_OFER.ID_DETALLE_OF,
        DETA_OFER.KILOS_TOTAL,
        DETA_OFER.PRECIO_TOTAL,
        DETA_OFER.FECHA_COSECHA,
        DETA_OFER.CERRADA,
        DETA_OFER.ID_USUARIO,
        OFER_PROD.ID_OFERTA,
        OFER_PROD.ID_SOLICITUD,
        DETA_SOLI.ID_PEDIDO,
        TRIM(CONCAT(CONCAT(USUA.NOMBRE, ' '), USUA.AP_PATERNO)) NOMBRE_USUARIO
    FROM DETALLE_OFERTA DETA_OFER
        INNER JOIN OFERTA_PRODUCTOR OFER_PROD
            ON DETA_OFER.ID_OFERTA = OFER_PROD.ID_OFERTA
        INNER JOIN USUARIO USUA
            ON DETA_OFER.ID_USUARIO = USUA.ID_USUARIO
        INNER JOIN DETALLE_SOLICITUD DETA_SOLI
            ON OFER_PROD.ID_SOLICITUD = DETA_SOLI.ID_SOLICITUD AND DETA_SOLI.ID_PEDIDO = DETA_OFER.ID_PEDIDO
);

/

CREATE OR REPLACE VIEW VIEW_DATOS_COTIZACION AS (
    SELECT 
        DETA_OFER.ID_DETALLE_OF,
        DETA_SOLI.ID_SOLICITUD,
        DETA_OFER.PRECIO_TOTAL,
        DETA_OFER.FECHA_COSECHA,
        DETA_OFER.CERRADA,
        ESPE.DES_ESPECIE,
        VARI.DES_VARIEDAD,
        USUA.ID_USUARIO,
        USUA.RUN_USUARIO,
        TRIM(CONCAT(CONCAT(USUA.NOMBRE, ' '), USUA.AP_PATERNO)) NOMBRE_USUARIO,
        CONCAT(CONCAT(USUA.DIRECCION, ', '), COMU.DES_COMUNA) DIRECCION,
        USUA.EMAIL CORREO,
        DETA_OFER.ID_PEDIDO,
        DETA_SOLI.KILOS,
        DETA_SOLI.KILOS_OBTE,
        ORDE.ID_ESTADO ID_ESTADO_ORDEN,
        SOLI.ID_PUBLICACION ID_ESTADO_PUBLICACION
    FROM DETALLE_OFERTA DETA_OFER
        INNER JOIN DETALLE_SOLICITUD DETA_SOLI
            ON DETA_OFER.ID_PEDIDO = DETA_SOLI.ID_PEDIDO
       INNER JOIN SOLICITUD SOLI
            ON DETA_SOLI.ID_SOLICITUD = SOLI.ID_SOLICITUD
        INNER JOIN VARIEDAD VARI
            ON DETA_OFER.ID_VARIEDAD = VARI.ID_VARIEDAD
        INNER JOIN ESPECIE ESPE
            ON VARI.ID_ESPECIE = ESPE.ID_ESPECIE
        INNER JOIN USUARIO USUA
            ON DETA_OFER.ID_USUARIO = USUA.ID_USUARIO
        INNER JOIN COMUNA COMU
            ON USUA.ID_COMUNA = COMU.ID_COMUNA
        LEFT JOIN ORDEN_COMPRA ORDE
            ON DETA_SOLI.ID_SOLICITUD = ORDE.ID_SOLICITUD
);

/

CREATE OR REPLACE VIEW VIEW_PEDIDOS_ACEPTADOS AS (
    SELECT
        ORDE_COMP.ID_ORDEN,
        ORDE_COMP.FECHA_RECEPCION,
        ORDE_COMP.ID_SOLICITUD,
        ORDE_COMP.ID_ESTADO ID_ESTADO_PEDIDO,
        ESTA_PEDI.DESC_ESTADO
    FROM
        ORDEN_COMPRA ORDE_COMP
            INNER JOIN ESTADO_PEDIDO ESTA_PEDI
                ON ORDE_COMP.ID_ESTADO = ESTA_PEDI.ID_ESTADO
);

/
     
CREATE OR REPLACE VIEW VIEW_CANTIDAD_SOLICITUDES_PENDIENTES AS (
    SELECT
        ESTA_SOLI.DES_ESTADO,
        COUNT(DISTINCT(SOLI.ID_SOLICITUD)) CANTIDAD_SOLICITUDES
    FROM
        SOLICITUD SOLI
            RIGHT OUTER JOIN ESTADO_SOLICITUD ESTA_SOLI
                ON SOLI.ID_ESTADO = ESTA_SOLI.ID_ESTADO
    WHERE
        SOLI.ID_ESTADO = 1
    GROUP BY
        ESTA_SOLI.DES_ESTADO
);

/

CREATE OR REPLACE VIEW VIEW_CANTIDAD_OC_RECHAZADAS AS (
    SELECT
        ESTA_PEDI.DESC_ESTADO,
        COUNT(DISTINCT(ORDEN.ID_ORDEN)) CANTIDAD_OC
    FROM
        ORDEN_COMPRA ORDEN
            RIGHT OUTER JOIN ESTADO_PEDIDO ESTA_PEDI
                ON ORDEN.ID_ESTADO = ESTA_PEDI.ID_ESTADO
    WHERE
        ORDEN.ID_ESTADO = 4
    GROUP BY
        ESTA_PEDI.DESC_ESTADO
);

/

CREATE OR REPLACE VIEW VIEW_CANTIDAD_PUBLICACIONES_X_ESTADO AS (
    SELECT 
        ESTA_PUBL.ID_ESTADO,
        ESTA_PUBL.DES_ESTADO,
        COUNT(DISTINCT(VIEW_LISTA.ID_SOLICITUD)) CANTIDAD_PUBLICACIONES
    FROM VIEW_LISTA_SOLICITUDES VIEW_LISTA
        RIGHT JOIN ESTADO_PUBLICACION ESTA_PUBL
            ON VIEW_LISTA.ID_PUBLICACION = ESTA_PUBL.ID_ESTADO
    WHERE
        VIEW_LISTA.ID_ESTADO = 2 OR VIEW_LISTA.ID_SOLICITUD IS NULL
    GROUP BY
        ESTA_PUBL.DES_ESTADO, ESTA_PUBL.ID_ESTADO
    --ORDER BY
        --ESTA_PUBL.ID_ESTADO
);
    
/

CREATE OR REPLACE VIEW VIEW_GANANCIAS_X_MES AS (
    SELECT
        MESES.ID_MES N_MES,
        SUM(MONTO) VENDIDO_MES
    FROM 
        PAGO PAG
            RIGHT JOIN 
                        (
                        SELECT
                            EXTRACT(MONTH FROM TO_DATE('2020-12-01', 'yyyy-mm-dd')) - (LEVEL - 1) ID_MES
                        FROM
                            DUAL
                        CONNECT BY
                            LEVEL <= 12
                        ) MESES
                ON TO_CHAR(PAG.FECHA_PAGO, 'MM') = MESES.ID_MES
    GROUP BY
        MESES.ID_MES        
);        

/

CREATE OR REPLACE VIEW VIEW_COSTOS_X_MES AS (
    SELECT
        MESES.ID_MES N_MES,
        SUM(COST.VALOR) COSTOS_MES
    FROM 
        COSTOS COST
        INNER JOIN STOCK_SOBRANTE STOCK
            ON COST.ID_ORDEN = STOCK.ID_ORDEN
        INNER JOIN VENTA_LOCAL VENT
            ON VENT.ID_STOCK = STOCK.ID_STOCK
        INNER JOIN PAGO PAG
            ON PAG.ID_VENTA_LOCAL = VENT.ID_VENTA_LOCAL
        RIGHT JOIN 
                        (
                        SELECT
                            EXTRACT(MONTH FROM TO_DATE('2020-12-01', 'yyyy-mm-dd')) - (LEVEL - 1) ID_MES
                        FROM
                            DUAL
                        CONNECT BY
                            LEVEL <= 12
                        ) MESES
                ON TO_CHAR(PAG.FECHA_PAGO, 'MM') = MESES.ID_MES
    GROUP BY
        MESES.ID_MES        
);

/

CREATE OR REPLACE VIEW VIEW_FRUTAS_DONADAS AS (
    SELECT      
        ESPECIE.DES_ESPECIE,
        VARIEDAD.DES_VARIEDAD,
        SUM(STOCK.KILOS) KILOS_DONADOS          
    FROM
        STOCK_SOBRANTE STOCK
            INNER JOIN VARIEDAD VARIEDAD
                ON STOCK.ID_VARIEDAD = VARIEDAD.ID_VARIEDAD
            INNER JOIN ESPECIE ESPECIE
                ON VARIEDAD.ID_ESPECIE = ESPECIE.ID_ESPECIE
    WHERE
    STOCK.FECHA_ESTIMADA_VENCIMIENTO < TO_DATE('03/12/2020','DD/MM/YYYY') AND STOCK.KILOS > 0
    GROUP BY
        ESPECIE.DES_ESPECIE, VARIEDAD.DES_VARIEDAD
);

/

CREATE OR REPLACE VIEW VIEW_PREFERENCIAS_BANCO AS (
    SELECT 
        BAN.DES_BANCO,
        COUNT(ID_PAGO) CANTIDAD_USADO
    FROM PAGO PAG
        INNER JOIN BANCO BAN
            ON PAG.ID_BANCO = BAN.ID_BANCO AND PAG.ID_BANCO <> -1
    GROUP BY
        BAN.DES_BANCO
);

/

CREATE OR REPLACE VIEW VIEW_PRODUCTORES_OFERTAS_APROBADAS AS (
    SELECT
        CONCAT(CONCAT(USUA.ID_USUARIO, ' - '), CONCAT(SUBSTR(USUA.NOMBRE, 0, INSTR(USUA.NOMBRE, ' ', 1)), USUA.AP_PATERNO)) NOMBRE_PRODUCTOR,
        COUNT(DETA_OFER.ID_PEDIDO) CANTIDAD_OFERTAS_APROBADAS
    FROM 
        DETALLE_OFERTA DETA_OFER
            INNER JOIN USUARIO USUA
                ON DETA_OFER.ID_USUARIO = USUA.ID_USUARIO
    WHERE
        DETA_OFER.CERRADA = 1
    GROUP BY
        USUA.ID_USUARIO,USUA.NOMBRE, USUA.AP_PATERNO
);

/

CREATE OR REPLACE VIEW VIEW_EXTERNO_ORDENES_RECHAZADAS AS (
    SELECT
        CONCAT(CONCAT(USUA.ID_USUARIO, ' - '), CONCAT(SUBSTR(USUA.NOMBRE, 0, INSTR(USUA.NOMBRE, ' ', 1)), USUA.AP_PATERNO)) NOMBRE_COMERCIANTE_EXT,
        COUNT(USUA.ID_USUARIO) CANTIDAD_ORDENES_RECHAZADAS
    FROM
        COSTOS COST
            INNER JOIN USUARIO USUA
                ON SUBSTR(SUBSTR(DESCRIPCION, INSTR(DESCRIPCION, ':') + 2, 1000), 0, INSTR(SUBSTR(DESCRIPCION, INSTR(DESCRIPCION, ':') + 2, 1000), ' ')) = USUA.ID_USUARIO
    WHERE
        SUBSTR(DESCRIPCION, 0, INSTR(DESCRIPCION, ' ') - 1) = 'Rechazada'
    GROUP BY
        USUA.ID_USUARIO,USUA.NOMBRE, USUA.AP_PATERNO
);

/

CREATE OR REPLACE VIEW VIEW_VENTA_LOCAL_EXTERNA AS (
    SELECT
        MESES.ID_MES N_MES,
        SUM(MONTO) VENDIDO_MES_LOCAL,
        VENDIDO_MES_EXTERNO
    FROM 
        PAGO PAG
            RIGHT JOIN (
                        SELECT
                            EXTRACT(MONTH FROM TO_DATE('2020-12-01', 'yyyy-mm-dd')) - (LEVEL - 1) ID_MES
                        FROM
                            DUAL
                        CONNECT BY
                            LEVEL <= 12
                        ) MESES
                ON TO_CHAR(PAG.FECHA_PAGO, 'MM') = MESES.ID_MES
            INNER JOIN (
                        SELECT
                            MESES.ID_MES N_MES,
                            SUM(MONTO) VENDIDO_MES_EXTERNO
                        FROM 
                            PAGO PAG
                                RIGHT JOIN (
                                            SELECT
                                                EXTRACT(MONTH FROM TO_DATE('2020-12-01', 'yyyy-mm-dd')) - (LEVEL - 1) ID_MES
                                            FROM
                                                DUAL
                                            CONNECT BY
                                                LEVEL <= 12
                                            ) MESES
                                    ON TO_CHAR(PAG.FECHA_PAGO, 'MM') = MESES.ID_MES
                        WHERE
                            PAG.ID_BANCO = -1 OR MONTO IS NULL
                        GROUP BY
                            MESES.ID_MES 
                        ) GANANCIAS_EXTERNO
            ON MESES.ID_MES = GANANCIAS_EXTERNO.N_MES
    WHERE
        PAG.ID_BANCO <> -1 OR MONTO IS NULL
    GROUP BY
        MESES.ID_MES, VENDIDO_MES_EXTERNO
);

/

CREATE OR REPLACE VIEW VIEW_HISTORIAL_COMERCIANTE AS (
    SELECT
        PAG.ID_VENTA_LOCAL N_VENTA,
        PAG.FECHA_PAGO FECHA_COMPRA,
        CONCAT(ESPE.DES_ESPECIE, CONCAT(' ', VARI.DES_VARIEDAD)) FRUTA,
        VENT_LOCA.KILOS_COMPRADOS,
        PAG.MONTO,
        VENT_LOCA.ID_USUARIO
    FROM
        PAGO PAG
            INNER JOIN VENTA_LOCAL VENT_LOCA
                ON PAG.ID_VENTA_LOCAL = VENT_LOCA.ID_VENTA_LOCAL
            INNER JOIN STOCK_SOBRANTE STOC_SOBRA
                ON VENT_LOCA.ID_STOCK = STOC_SOBRA.ID_STOCK
            INNER JOIN VARIEDAD VARI
                ON STOC_SOBRA.ID_VARIEDAD = VARI.ID_VARIEDAD
            INNER JOIN ESPECIE ESPE
                ON VARI.ID_ESPECIE = ESPE.ID_ESPECIE
);

/

CREATE OR REPLACE VIEW VIEW_HISTORIAL_EXTERNO AS (
    SELECT
        ORDE_COMP.ID_SOLICITUD N_VENTA,
        ORDE_COMP.FECHA_RECEPCION,
        CONCAT(ESPE.DES_ESPECIE, CONCAT(' ', VARI.DES_VARIEDAD)) FRUTA,
        DETA_SOLI.KILOS KILOS_SOLICITADOS,
        COST.VALOR MONTO,
        TRIM(SUBSTR(COST.DESCRIPCION, 0, INSTR(COST.DESCRIPCION, ' '))) ESTADO,
        ROW_NUMBER()OVER (PARTITION BY ORDE_COMP.ID_SOLICITUD ORDER BY ORDE_COMP.ID_SOLICITUD) AS N_REP_SOLICITUD,
        SUBSTR(SUBSTR(COST.DESCRIPCION, INSTR(COST.DESCRIPCION, ':') + 2, 1000), 0, INSTR(SUBSTR(COST.DESCRIPCION, INSTR(COST.DESCRIPCION, ':') + 2, 1000), ' ')) ID_USUARIO
    FROM
        COSTOS COST
            INNER JOIN ORDEN_COMPRA ORDE_COMP
                ON COST.ID_ORDEN = ORDE_COMP.ID_ORDEN
            INNER JOIN DETALLE_SOLICITUD DETA_SOLI
                ON ORDE_COMP.ID_SOLICITUD = DETA_SOLI.ID_SOLICITUD
            INNER JOIN VARIEDAD VARI
                ON DETA_SOLI.ID_VARIEDAD = VARI.ID_VARIEDAD
            INNER JOIN ESPECIE ESPE
                ON VARI.ID_ESPECIE = ESPE.ID_ESPECIE
);

/

CREATE OR REPLACE VIEW VIEW_HISTORIAL_PRODUCTOR AS (
    SELECT
        DETA_OFER.ID_DETALLE_OF N_OFERTA,
        DETA_OFER.ID_PEDIDO,
        DETA_OFER.FECHA_OFERTA,
        CONCAT(ESPE.DES_ESPECIE, CONCAT(' ', VARI.DES_VARIEDAD)) FRUTA,
        DETA_OFER.KILOS_TOTAL KILOS_VENDIDOS,
        DETA_OFER.PRECIO_TOTAL,
        DETA_OFER.CERRADA,
        ROW_NUMBER()OVER (PARTITION BY DETA_OFER.ID_PEDIDO ORDER BY DETA_OFER.CERRADA DESC) AS N_REP_OFERTA,
        DETA_OFER.ID_USUARIO
    FROM DETALLE_OFERTA DETA_OFER
        INNER JOIN VARIEDAD VARI
            ON DETA_OFER.ID_VARIEDAD = VARI.ID_VARIEDAD
        INNER JOIN ESPECIE ESPE
            ON VARI.ID_ESPECIE = ESPE.ID_ESPECIE
);
