"""
Django settings for proyectoBestFruit project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2-@xpu5m8-e6=$y!t+%qb_*y&zz(%h4vvj@pa^s!)6#86i0rgk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.portafolioBestFruit.cl','portafolioBestFruit.cl','10.0.2.15','*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portalVentas.apps.PortalventasConfig',
    'administrador.apps.AdministradorConfig',
    'pwa'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'proyectoBestFruit.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyectoBestFruit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'localhost:51521/xe',
        'USER': 'admin_django',
        'PASSWORD': 'admin1234'
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.oracle',
    #     'NAME': '192.168.0.10:1521/xe',
    #     'USER': 'c##feriaVirtual',
    #     'PASSWORD': 'feriavirtual'
    # },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-cl'

USE_THOUSAND_SEPARATOR = True
USE_L10N = True


TIME_ZONE = 'UTC'

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATIC_ROOT = '/portalVentas/static/'
STATIC_URL = '/static/'
STATICFIES_DIRS =[
    os.path.join(BASE_DIR, 'static')
]

LOGIN_REDIRECT_URL = '/'


# PWA
PWA_SERVICE_WORKER_PATH = '/var/www/portafolioBestFruit/Proyecto/BestFruit/sw.js'
# PWA - MANIFEST
PWA_APP_NAME = 'Best Fruit'
PWA_APP_DESCRIPTION = "En Best Fruit somos el puente de conexión entre los productores locales que desean exportar su fruta y las empresas extranjeras que necesitan aquellos productos. A su vez, somos una tienda virtual que facilita el abastecimiento de los hogares chilenos."
PWA_APP_THEME_COLOR = '#10b981'
PWA_APP_BACKGROUND_COLOR = '#10b981'
PWA_APP_ORIENTATION = 'portrait'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src' : '/static/img/iconsPwa/1024.png',
        'sizes' : '1024x1024',
        'type' : 'image/png'
    },
    {
        'src' : '/static/img/iconsPwa/512.png',
        'sizes' : '512x512',
        'type' : 'image/png'
    },
    {
        'src' : '/static/img/iconsPwa/256.png',
        'sizes' : '256x256',
        'type' : 'image/png'
    },
    {
        'src' : '/static/img/iconsPwa/128.png',
        'sizes' : '128x128',
        'type' : 'image/png'
    },
    {
        'src' : '/static/img/iconsPwa/64.png',
        'sizes' : '64x64',
        'type' : 'image/png'
    },
    {
        'src' : '/static/img/iconsPwa/32.png',
        'sizes' : '32x32',
        'type' : 'image/png'
    },
    {
        'src' : '/static/img/iconsPwa/16.png',
        'sizes' : '16x16',
        'type' : 'image/png'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es-CL'