# Generated by Django 3.1.2 on 2020-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calidad',
            fields=[
                ('id_calidad', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Calidad',
                'db_table': 'calidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id_calificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('des_calificacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Calificacion',
                'db_table': 'calificacion',
                'get_latest_by': 'id_calificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.IntegerField(primary_key=True, serialize=False)),
                ('des_comuna', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Comuna',
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('vigencia', models.CharField(max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Contrato',
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Costos',
            fields=[
                ('id_costo', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Costos',
                'db_table': 'costos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOferta',
            fields=[
                ('id_detalle_of', models.IntegerField(primary_key=True, serialize=False)),
                ('kilos_total', models.IntegerField()),
                ('precio_total', models.IntegerField()),
                ('fecha_cosecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'DetalleOferta',
                'db_table': 'detalle_oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('kilos', models.DecimalField(decimal_places=4, max_digits=14)),
            ],
            options={
                'verbose_name_plural': 'DetalleSolicitud',
                'db_table': 'detalle_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.IntegerField(primary_key=True, serialize=False)),
                ('des_especie', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Especie',
                'db_table': 'especie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoContrato',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('des_estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'EstadoContrato',
                'db_table': 'estado_contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEmpresa',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('des_estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'EstadoEmpresa',
                'db_table': 'estado_empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'EstadoPedido',
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoSolicitud',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('des_estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'EstadoSolicitud',
                'db_table': 'estado_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoUsuario',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('des_estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'EstadoUsuario',
                'db_table': 'estado_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoVenta',
            fields=[
                ('id_estado', models.IntegerField(primary_key=True, serialize=False)),
                ('des_estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'EstadoVenta',
                'db_table': 'estado_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.IntegerField(primary_key=True, serialize=False)),
                ('desc_imagen', models.CharField(max_length=100)),
                ('ext_imagen', models.CharField(max_length=6)),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Imagen',
                'db_table': 'imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OfertaProductor',
            fields=[
                ('id_oferta', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'OfertaProductor',
                'db_table': 'oferta_productor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_orden', models.IntegerField(primary_key=True, serialize=False)),
                ('diferencia_fruta', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'OrdenCompra',
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('kilos_comprados', models.IntegerField()),
                ('usuario', models.CharField(max_length=150)),
                ('especie', models.IntegerField()),
                ('variedad', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Pago',
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pais',
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.IntegerField(primary_key=True, serialize=False)),
                ('des_provincia', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Provincia',
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Puntos',
            fields=[
                ('id_puntos', models.IntegerField(primary_key=True, serialize=False)),
                ('des_puntos', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Puntos',
                'db_table': 'puntos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.IntegerField(primary_key=True, serialize=False)),
                ('des_region', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Region',
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.IntegerField(primary_key=True, serialize=False)),
                ('des_rol', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Rol',
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Solicitud',
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockSobrante',
            fields=[
                ('id_stock', models.IntegerField(primary_key=True, serialize=False)),
                ('kilos', models.IntegerField(blank=True, null=True)),
                ('fecha_cosecha', models.DateField(blank=True, null=True)),
                ('fecha_estimada_vencimiento', models.DateField(blank=True, null=True)),
                ('precio_kilo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'StockSobrante',
                'db_table': 'stock_sobrante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('run_usuario', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('ap_paterno', models.CharField(max_length=25)),
                ('ap_materno', models.CharField(max_length=25)),
                ('fecha_nac', models.DateField()),
                ('email', models.CharField(max_length=250, unique=True)),
                ('direccion', models.CharField(max_length=150)),
                ('num_celular', models.IntegerField()),
                ('clave', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Usuario',
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('id_variedad', models.IntegerField(primary_key=True, serialize=False)),
                ('des_variedad', models.CharField(max_length=50)),
                ('dias_vencimiento', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Variedad',
                'db_table': 'variedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaLocal',
            fields=[
                ('id_venta_local', models.IntegerField(primary_key=True, serialize=False)),
                ('kilos_iniciales', models.IntegerField()),
                ('kilos_comprados', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'VentaLocal',
                'db_table': 'venta_local',
                'managed': False,
            },
        ),
    ]
