# Generated by Django 3.1.2 on 2020-11-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalVentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPublicacion',
            fields=[
                ('id_publicacion', models.IntegerField(primary_key=True, serialize=False)),
                ('des_estado', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'EstadoPublicacion',
                'db_table': 'estado_publicacion',
                'managed': False,
            },
        ),
    ]
