# Generated by Django 3.1.2 on 2020-11-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalVentas', '0002_estadopublicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.IntegerField(primary_key=True, serialize=False)),
                ('des_banco', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Banco',
                'db_table': 'banco',
                'managed': False,
            },
        ),
    ]
